# Generated by Django 2.2.6 on 2019-10-30 06:41

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_title', models.CharField(max_length=255)),
                ('second_title', models.CharField(max_length=255)),
                ('content', tinymce.models.HTMLField(default=None)),
                ('image1', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=0, size=[400, 400], upload_to='about')),
                ('image2', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=0, size=[400, 400], upload_to='about')),
                ('signature', models.ImageField(blank=True, upload_to='about')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('category_slug', models.SlugField(default=None)),
                ('category_image', models.ImageField(default=None, upload_to='category')),
            ],
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_title', models.CharField(max_length=255)),
                ('second_title', models.CharField(max_length=255)),
                ('content', models.TextField(default=None)),
                ('small_content1', models.TextField(default=None)),
                ('small_content2', models.TextField(default=None)),
                ('small_content3', models.TextField(default=None)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=0, size=[272, 300], upload_to='core_value')),
            ],
        ),
        migrations.CreateModel(
            name='Enquery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256)),
                ('email', models.CharField(blank=True, max_length=256)),
                ('mobile', models.CharField(blank=True, max_length=256)),
                ('subject', models.CharField(blank=True, max_length=256)),
                ('message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='OurSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default=None, max_length=255)),
                ('title1', models.CharField(default=None, max_length=255)),
                ('content1', models.TextField(default=None)),
                ('title2', models.CharField(default=None, max_length=255)),
                ('content2', models.TextField(default=None)),
                ('title3', models.CharField(default=None, max_length=255)),
                ('content3', models.TextField(default=None)),
                ('image', django_resized.forms.ResizedImageField(crop=None, default=None, force_format=None, keep_meta=True, quality=0, size=[750, 750], upload_to='our_skill')),
            ],
        ),
        migrations.CreateModel(
            name='SiteAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default=None, max_length=256)),
                ('landline', models.CharField(default=None, max_length=256)),
                ('email', models.CharField(default=None, max_length=256)),
                ('web_link', models.CharField(default=None, max_length=256)),
                ('address', models.TextField(default=None)),
                ('footer_content', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_title', models.CharField(max_length=255)),
                ('title_content', tinymce.models.HTMLField(default=None)),
                ('title', models.CharField(max_length=255)),
                ('image', django_resized.forms.ResizedImageField(crop=None, default=None, force_format=None, keep_meta=True, quality=0, size=[1600, 900], upload_to='slider')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(default=None, max_length=256)),
                ('twitter', models.CharField(default=None, max_length=256)),
                ('flickr', models.CharField(default=None, max_length=256)),
                ('linkedin', models.CharField(default=None, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=256)),
                ('content', models.TextField(default=None)),
                ('image', models.ImageField(default=None, upload_to='why_choose_us')),
            ],
        ),
        migrations.CreateModel(
            name='PostDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_content', tinymce.models.HTMLField(default=None)),
                ('slider_image1', django_resized.forms.ResizedImageField(crop=None, default=None, force_format=None, keep_meta=True, quality=0, size=[1000, 500], upload_to='post_details')),
                ('slider_image2', django_resized.forms.ResizedImageField(crop=None, default=None, force_format=None, keep_meta=True, quality=0, size=[1000, 500], upload_to='post_details')),
                ('slider_image3', django_resized.forms.ResizedImageField(crop=None, default=None, force_format=None, keep_meta=True, quality=0, size=[1000, 500], upload_to='post_details')),
                ('title1', models.CharField(max_length=255)),
                ('content1', tinymce.models.HTMLField(default=None)),
                ('image1', django_resized.forms.ResizedImageField(crop=None, default=None, force_format=None, keep_meta=True, quality=0, size=[456, 286], upload_to='post_details')),
                ('title2', models.CharField(max_length=255)),
                ('content2', tinymce.models.HTMLField(default=None)),
                ('image2', django_resized.forms.ResizedImageField(crop=None, default=None, force_format=None, keep_meta=True, quality=0, size=[456, 303], upload_to='post_details')),
                ('sub_title1', models.CharField(max_length=255)),
                ('sub_title2', models.CharField(max_length=255)),
                ('sub_title3', models.CharField(max_length=255)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='skillfrontend.Category')),
            ],
        ),
    ]
