# Generated by Django 2.2.6 on 2019-10-30 07:52

from django.db import migrations, models
import django_resized.forms
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('skillfrontend', '0002_auto_20191030_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corevalue',
            name='content',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='corevalue',
            name='first_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='corevalue',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[272, 300], upload_to='core_value'),
        ),
        migrations.AlterField(
            model_name='corevalue',
            name='second_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='corevalue',
            name='small_content1',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='corevalue',
            name='small_content2',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='corevalue',
            name='small_content3',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[1600, 900], upload_to='slider'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='small_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title_content',
            field=tinymce.models.HTMLField(default=None, null=True),
        ),
    ]
