# Generated by Django 2.2.6 on 2019-10-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillfrontend', '0004_auto_20191030_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.CharField(max_length=256, null=True)),
                ('receive_email', models.CharField(max_length=256, null=True)),
            ],
            options={
                'verbose_name_plural': 'Email Management',
            },
        ),
    ]
